// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALbooDkwJPwQxnhQpkdo9V4PQXCjbkSuw',
    appId: '1:268097960695:web:fa3a2158c54218fb3ab1f2',
    messagingSenderId: '268097960695',
    projectId: 'finalprojectbsc-abf6f',
    authDomain: 'finalprojectbsc-abf6f.firebaseapp.com',
    storageBucket: 'finalprojectbsc-abf6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUZyCpOe8Wp6FVt3axdOLFkPUXN2xTLqA',
    appId: '1:268097960695:android:2ad96012ac4d78a63ab1f2',
    messagingSenderId: '268097960695',
    projectId: 'finalprojectbsc-abf6f',
    storageBucket: 'finalprojectbsc-abf6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5dhebtqdgwydO4lGzEP0Vf5rHO5K0po8',
    appId: '1:268097960695:ios:ea74a3346601911b3ab1f2',
    messagingSenderId: '268097960695',
    projectId: 'finalprojectbsc-abf6f',
    storageBucket: 'finalprojectbsc-abf6f.appspot.com',
    iosClientId: '268097960695-1q64clqd6pc7feg3dlun77g2djubcttl.apps.googleusercontent.com',
    iosBundleId: 'dev.navod.flutter.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5dhebtqdgwydO4lGzEP0Vf5rHO5K0po8',
    appId: '1:268097960695:ios:ea74a3346601911b3ab1f2',
    messagingSenderId: '268097960695',
    projectId: 'finalprojectbsc-abf6f',
    storageBucket: 'finalprojectbsc-abf6f.appspot.com',
    iosClientId: '268097960695-1q64clqd6pc7feg3dlun77g2djubcttl.apps.googleusercontent.com',
    iosBundleId: 'dev.navod.flutter.finalProject',
  );
}
